"""Run the full UAVGuard demo workflow."""

from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from uavguard.agents.orchestrator import UAVGuardOrchestrator
from uavguard.api.schemas import FlightRequest
from uavguard.config import get_settings
from uavguard.knowledge_base.db import initialize_database
from uavguard.knowledge_base.ingest_drones import ingest_directory
from uavguard.policy.ingest_policies import ingest_policy_directory


SAMPLE_POLICY_TEXT = """Synthetic FAA-aligned demo guidance for UAVGuard research.
This file is illustrative demo content and must be replaced with official FAA documents for real evaluations.

Rule 1: Daylight small UAS operations may proceed when the remote pilot maintains visual line of sight with the aircraft.
Rule 2: Night operations require anti-collision lighting and additional review before launch.
Rule 3: Missions should remain within the planned route corridor and avoid restricted cells generated by the simulator.
Rule 4: Missions should be paused when environmental conditions prevent safe control of the aircraft.
"""


def ensure_sample_policy(settings) -> Path:
    policy_files = [
        path
        for path in settings.faa_docs_dir.iterdir()
        if path.is_file() and path.suffix.lower() in {".txt", ".pdf"}
    ]
    if policy_files:
        return policy_files[0]
    sample_path = settings.faa_docs_dir / "sample_faa_guidance.txt"
    sample_path.write_text(SAMPLE_POLICY_TEXT, encoding="utf-8")
    return sample_path


def main() -> None:
    settings = get_settings()
    initialize_database(settings.database_path)
    drone_count = ingest_directory(settings.raw_data_dir, settings.database_path)
    policy_path = ensure_sample_policy(settings)
    policy_chunks = ingest_policy_directory(settings.faa_docs_dir, settings)

    sample_request_path = settings.sample_requests_dir / "sample_flight_request.json"
    request_payload = json.loads(sample_request_path.read_text(encoding="utf-8"))
    request = FlightRequest.model_validate(request_payload)
    response = UAVGuardOrchestrator(settings).run(request)

    artifacts_dir = settings.processed_data_dir / "artifacts"
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    decision_path = artifacts_dir / "demo_decision.json"
    decision_path.write_text(response.model_dump_json(indent=2), encoding="utf-8")

    print(f"Drone records ingested: {drone_count}")
    print(f"Policy source: {policy_path}")
    print(f"Policy chunks indexed: {policy_chunks}")
    print(f"Decision artifact: {decision_path}")
    print(response.model_dump_json(indent=2))


if __name__ == "__main__":
    main()
